### ISSUE TITLE
Week 1 To Do's

### ISSUE THREAD

**Issue by Shan-non** [UBC-MDS/maternal_health_classification#1]
Nelli 
- environment file and conda lock file

Joseph
- organization of github documents

Shannon
- README file

Unassigned (currently):
- license file
- contributing file
- finish the code of conduct file
- analysis (need to split up the parts of analysis and distribute evenly)

**Comment by hovhannisyannelli** [comment]
Nelli 

1. EDA
2. contributing file
3. team work contract after PR

**Comment by Shan-non** [comment]
Shannon:
1. README file
2. code of conduct file
3. Naive Bayes model on our dataset

**Comment by JiaQuanLim** [comment]
Okay thanks, I will do the following:

1. Analysis - modelling (Logistic Regression)
2. License file
3. Team work contract Expectation and meeting points

**Comment by hovhannisyannelli** [comment]
Everyone completed their ToDOs
