### ISSUE TITLE
Could not run docker-compose up --build

### ISSUE THREAD

**Issue by Shan-non** [UBC-MDS/maternal_health_classification#33]
I received the error: 
 "✘ jupyter-notebook Error Head "https://registry-1.docker.io/v2/123456789nelli/maternal...                         0.9s
Error response from daemon: Head "https://registry-1.docker.io/v2/123456789nelli/maternal_health_classification/manifests/latest": unauthorized: incorrect username or password" 

I also tried the same command without the --build flag and received the same result.

**Comment by Shan-non** [comment]
![image](https://github.com/user-attachments/assets/02a336e2-99dd-4bdb-8fc7-31a867d2fe28)

**Comment by Shan-non** [comment]
Fixed via running the following in my terminal:
`docker login`
then typing my docker username and password when prompted
then re-trying docker compose up

**Comment by hovhannisyannelli** [comment]
The solution was running `docker login` command
