### ISSUE TITLE
Conda-lock does not work for Mac-s

### ISSUE THREAD

**Issue by hovhannisyannelli** [UBC-MDS/maternal_health_classification#4]
When trying to use conda-lock it gives an error due to mamba issues

**Comment by hovhannisyannelli** [comment]
Solution: I have removed the .conda and .miniforge3 files. Then downloaded and installed Miniforge3

Visit the [Miniforge Releases](https://conda-forge.org/miniforge/) page and download the latest version of Miniforge3 for your system.

Run the Installation Script

- {HOME}/Downloads/Miniforge3.sh -b -p "${HOME}/miniforge3"
- source "${HOME}/miniforge3/etc/profile.d/conda.sh"
- conda activate
- conda init
- mamba install --no-channel-priority conda-forge::mamba>=2.0 conda-canary/label/dev::conda-libmamba-solver
- conda install pandas jupyterlab jupyterlab-git jupyterlab-spellchecker
- pip install otter-grader

**Comment by JiaQuanLim** [comment]
Thanks Nelli, I did encounter the same issue too 👍

**Comment by hovhannisyannelli** [comment]
We were able to resolve the issue
