### ISSUE TITLE
Validation check failed for values outside range in Heart Rate column

### ISSUE THREAD

**Issue by Shan-non** [UBC-MDS/maternal_health_classification#40]
Our dataframe failed validation checks for two rows being outside the range in the HeartRate column. Two rows had a heart rate of 7. 

This is clearly a mistake, no human's heart rate is 7, so I vote we drop these two rows.

**Comment by JiaQuanLim** [comment]
Sounds reasonable, it should be dropped

**Comment by Shan-non** [comment]
Dropping two rows then!
